version: "3.7"

services:
  postgres_conecta:
    container_name: postgres_conecta_modadb
    image: postgres:16
    environment:
      POSTGRES_USER: conecta
      POSTGRES_PASSWORD: conecta
      POSTGRES_DB: conecta_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 